import { createContext, useContext, useState, useEffect, useCallback } from 'react';

const LanguageContext = createContext(null);
const STORAGE_KEY = 'agrilens_lang';

// ── Translation Dictionary ──
const translations = {
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.myCrop': 'My Crop',
    'nav.scanner': 'Scanner',
    'nav.weather': 'Weather',
    'nav.encyclopedia': 'Encyclopedia',
    'nav.community': 'Community',
    'nav.logout': 'Log Out',

    // Home
    'home.welcome': 'Welcome back,',
    'home.overview': "Here's your farm overview for today",
    'home.currentCrop': 'Current Crop',
    'home.weather': "Today's Weather",
    'home.season': 'Current Season',
    'home.tipOfDay': 'Tip of the Day',
    'home.quickAccess': 'Quick Access',
    'home.latestNews': 'Latest Agriculture News',
    'home.enableLocation': 'Enable location',
    'home.detecting': 'Detecting...',
    'home.cropScanner': 'Crop Scanner',
    'home.cropScannerDesc': 'AI-powered disease detection and treatment plans',
    'home.weatherPlanner': 'Weather Planner',
    'home.weatherPlannerDesc': '7-day forecast with irrigation scheduling',
    'home.encyclopedia': 'Encyclopedia',
    'home.encyclopediaDesc': 'Complete crop profiles and growing guides',
    'home.myCrop': 'My Crop',
    'home.myCropDesc': 'Your personalized crop dashboard and history',

    // Scanner
    'scanner.title': 'Crop Scanner',
    'scanner.subtitle': 'Upload or capture a photo of your crop for AI-powered disease analysis',
    'scanner.dropPhoto': 'Drop your crop photo here',
    'scanner.browse': 'or click to browse — supports JPEG, PNG, WebP',
    'scanner.upload': 'Upload Photo',
    'scanner.takePhoto': 'Take Photo',
    'scanner.analyzing': 'Analyzing your crop...',
    'scanner.wait': 'This may take a few seconds',
    'scanner.failed': 'Analysis Failed',
    'scanner.tryAgain': 'Try again',
    'scanner.scanAnother': 'Scan another crop',
    'scanner.tips': 'Tips for Best Results',
    'scanner.shopBtn': 'Shop Recommendations',

    // Weather
    'weather.title': 'Weather & Irrigation Planner',
    'weather.subtitle': '7-day forecast with AI-powered irrigation scheduling',
    'weather.locationRequired': 'Location Required',
    'weather.retry': 'Retry',
    'weather.forecast': '7-Day Forecast',
    'weather.generatePlan': 'Generate Irrigation Plan',
    'weather.cropName': 'Crop Name',
    'weather.generating': 'Generating...',
    'weather.genPlan': 'Generate Plan',
    'weather.weeklySummary': 'Weekly Summary',
    'weather.dailySchedule': 'Daily Irrigation Schedule',
    'weather.pesticides': 'Recommended Pesticides for this Weather',
    'weather.irrigationTips': 'Irrigation Tips',
    'weather.agriIndex': 'Agricultural Weather Index',
    'weather.soilMoisture': 'Soil Moisture',
    'weather.soilTemp': 'Soil Temperature',
    'weather.evapotranspiration': 'ET₀ (Reference)',
    'weather.sunshine': 'Sunshine',
    'weather.alerts': 'Weather Risk Alerts',
    'weather.humidity': 'Humidity',

    // Encyclopedia
    'encyclopedia.title': 'Crop Encyclopedia',
    'encyclopedia.subtitle': 'Search crops and get AI-generated growing guides',
    'encyclopedia.search': 'Search crops by name or category...',
    'encyclopedia.backToCrops': 'Back to crops',
    'encyclopedia.generating': 'Generating profile for',

    // My Crop
    'mycrop.title': 'My Crop',
    'mycrop.subtitle': 'Your current crop status and scan history',
    'mycrop.rescan': 'Re-scan Crop',
    'mycrop.viewIrrigation': 'View Irrigation Plan',
    'mycrop.noScan': 'No crop scanned yet',
    'mycrop.noScanDesc': 'Scan your first crop to start tracking its health and get personalized care plans.',
    'mycrop.scanFirst': 'Scan Your First Crop',
    'mycrop.history': 'Scan History',

    // Landing
    'landing.getStarted': 'Get Started',
    'landing.createProfile': 'Create your farmer profile to begin',
    'landing.welcomeBack': 'Welcome Back',
    'landing.enterName': 'Enter your name to continue',
    'landing.fullName': 'Full Name *',
    'landing.phone': 'Phone Number',
    'landing.village': 'Village / Town',
    'landing.create': 'Create Profile',
    'landing.continue': 'Continue',
    'landing.hasProfile': 'Already have a profile? Quick login',
    'landing.newHere': 'New here? Create a profile',
    'landing.heroTitle1': 'Smarter farming',
    'landing.heroTitle2': 'starts here.',
    'landing.heroDesc': 'Scan your crops, detect diseases instantly, get precise treatment plans, and plan irrigation with AI — all from your phone.',
    'landing.tag': 'AI-Powered Crop Intelligence',

    // Agent
    'agent.title': 'AgriLens AI',
    'agent.subtitle': 'Your farming assistant',
    'agent.placeholder': 'Ask about crops, weather, diseases...',
    'agent.greeting': "Hi! I'm your AgriLens farming assistant. Ask me anything about crops, diseases, fertilizers, weather, or farming practices.",

    // EShop
    'eshop.title': 'Recommended Products',
    'eshop.subtitle': 'Based on your crop analysis',
    'eshop.fertilizers': 'Suggested Fertilizers',
    'eshop.pesticides': 'Recommended Pesticides',
    'eshop.organic': 'Organic Alternatives',
    'eshop.comingSoon': 'Coming Soon',
    'eshop.addToCart': 'Add to Cart',
    'eshop.close': 'Close',

    // Common
    'common.healthy': 'Healthy',
    'common.loading': 'Loading...',

    // Community
    'comm.title': 'Agri Community',
    'comm.subtitle': 'Connect, share innovations, and grow together',
    'comm.placeholder': 'Share an update, ask a question, or post a new innovation...',
    'comm.addImage': 'Add Image',
    'comm.addLink': 'Add Innovation Link',
    'comm.post': 'Post',
    'comm.you': 'You',
    'comm.justNow': 'Just now',
    'comm.verified': 'Verified Innovator',
    'comm.purchase': 'Purchase / View Tool Details',
    'comm.trending': 'Trending in Agri',
    'comm.topInnovators': 'Top Innovators',
    'comm.follow': 'Follow',
    'comm.tech': 'Technology',
    'comm.cropsCat': 'Crops',
    'comm.market': 'Market',
    'comm.innovationCat': 'Innovation',
    'comm.posts': 'posts',

    // Landing Update
    'landing.featDetect': 'Instant Disease Detection',
    'landing.featDetectDesc': 'Upload a photo and get AI analysis in seconds',
    'landing.featPlan': 'Personalized Crop Plans',
    'landing.featPlanDesc': 'Irrigation, pesticide, and care schedules for your crop',
    'landing.featWeather': 'Weather Intelligence',
    'landing.featWeatherDesc': '7-day forecast with smart farming recommendations',
    'landing.loginPhonePass': 'Enter your phone and password to continue',
    'landing.namePlaceholder': 'Enter your name',
    'landing.phoneReq': 'Phone Number *',
    'landing.password': 'Password *',
    'landing.locPlaceholder': 'Optional',
    'landing.errNameRequired': 'Name is required to register.',
    'landing.errPhoneRequired': 'Phone number is required.',
    'landing.errPassLengths': 'Password must be at least 4 characters long.',
    'landing.stat1': 'Crop varieties supported',
    'landing.stat2': 'Disease detection accuracy',
    'landing.stat3': 'Weather & irrigation data',
    'landing.stat3val': 'Free',
    'landing.stat4': 'AI-generated reports',
    'landing.stat4val': 'Instant',

    // Report
    'report.type': 'Type',
    'report.dosage': 'Dosage',
    'report.apply': 'Apply',
    'report.frequency': 'Frequency',
    'report.warning': 'Warning',
    'report.close': 'Close',
    'report.saveAsImage': 'Save as Image',
    'report.downloadPdf': 'Download PDF',
    'report.share': 'Share',
    'report.diseaseDetected': 'Disease Detected',
    'report.treatmentPlan': 'Treatment Plan',
    'report.recommendedPesticides': 'Recommended Pesticides',
    'report.organicAlternatives': 'Organic Alternatives',
    'report.fertilizerSuggestions': 'Fertilizer Suggestions',
    'report.cropCareTips': 'Crop Care Tips',
    'report.analyzedBy': 'Analyzed by AgriLens AI',
    'report.scanAnother': 'Scan another leaf',
  },

  hi: {
    'nav.home': 'होम',
    'nav.myCrop': 'मेरी फसल',
    'nav.scanner': 'स्कैनर',
    'nav.weather': 'मौसम',
    'nav.encyclopedia': 'विश्वकोश',
    'nav.community': 'समुदाय',
    'nav.logout': 'लॉग आउट',

    'home.welcome': 'वापसी पर स्वागत है,',
    'home.overview': 'आज का आपका खेत अवलोकन',
    'home.currentCrop': 'वर्तमान फसल',
    'home.weather': 'आज का मौसम',
    'home.season': 'वर्तमान मौसम',
    'home.tipOfDay': 'आज की सलाह',
    'home.quickAccess': 'त्वरित पहुंच',
    'home.latestNews': 'ताज़ा कृषि समाचार',
    'home.enableLocation': 'स्थान सक्षम करें',
    'home.detecting': 'पता लगा रहे...',
    'home.cropScanner': 'फसल स्कैनर',
    'home.cropScannerDesc': 'AI-संचालित रोग पहचान और उपचार योजना',
    'home.weatherPlanner': 'मौसम योजनाकार',
    'home.weatherPlannerDesc': '7 दिन का पूर्वानुमान और सिंचाई योजना',
    'home.encyclopedia': 'विश्वकोश',
    'home.encyclopediaDesc': 'फसल प्रोफाइल और उगाने की मार्गदर्शिका',
    'home.myCrop': 'मेरी फसल',
    'home.myCropDesc': 'व्यक्तिगत फसल डैशबोर्ड और इतिहास',

    'scanner.title': 'फसल स्कैनर',
    'scanner.subtitle': 'AI विश्लेषण के लिए अपनी फसल की फोटो अपलोड करें',
    'scanner.dropPhoto': 'अपनी फसल की फोटो यहां डालें',
    'scanner.browse': 'या ब्राउज़ करें — JPEG, PNG, WebP',
    'scanner.upload': 'फोटो अपलोड',
    'scanner.takePhoto': 'फोटो लें',
    'scanner.analyzing': 'फसल का विश्लेषण...',
    'scanner.wait': 'कुछ सेकंड लग सकते हैं',
    'scanner.failed': 'विश्लेषण विफल',
    'scanner.tryAgain': 'पुनः प्रयास करें',
    'scanner.scanAnother': 'दूसरी फसल स्कैन करें',
    'scanner.tips': 'बेहतर परिणाम के लिए सुझाव',
    'scanner.shopBtn': 'उत्पाद सुझाव',

    'weather.title': 'मौसम और सिंचाई योजनाकार',
    'weather.subtitle': '7 दिन का पूर्वानुमान और AI सिंचाई नियोजन',
    'weather.locationRequired': 'स्थान आवश्यक',
    'weather.retry': 'पुनः प्रयास',
    'weather.forecast': '7 दिन का पूर्वानुमान',
    'weather.generatePlan': 'सिंचाई योजना बनाएं',
    'weather.cropName': 'फसल का नाम',
    'weather.generating': 'बना रहे हैं...',
    'weather.genPlan': 'योजना बनाएं',
    'weather.weeklySummary': 'साप्ताहिक सारांश',
    'weather.dailySchedule': 'दैनिक सिंचाई अनुसूची',
    'weather.pesticides': 'इस मौसम के लिए कीटनाशक',
    'weather.irrigationTips': 'सिंचाई सुझाव',
    'weather.agriIndex': 'कृषि मौसम सूचकांक',
    'weather.soilMoisture': 'मिट्टी की नमी',
    'weather.soilTemp': 'मिट्टी का तापमान',
    'weather.evapotranspiration': 'वाष्पीकरण (ET₀)',
    'weather.sunshine': 'धूप',
    'weather.alerts': 'मौसम जोखिम चेतावनी',
    'weather.humidity': 'आर्द्रता',

    'encyclopedia.title': 'फसल विश्वकोश',
    'encyclopedia.subtitle': 'AI-जनित फसल मार्गदर्शिकाएं खोजें',
    'encyclopedia.search': 'फसल का नाम या श्रेणी खोजें...',
    'encyclopedia.backToCrops': 'वापस फसलों पर',
    'encyclopedia.generating': 'प्रोफाइल बना रहे हैं',

    'mycrop.title': 'मेरी फसल',
    'mycrop.subtitle': 'वर्तमान फसल की स्थिति और स्कैन इतिहास',
    'mycrop.rescan': 'पुनः स्कैन करें',
    'mycrop.viewIrrigation': 'सिंचाई योजना देखें',
    'mycrop.noScan': 'अभी तक कोई फसल स्कैन नहीं',
    'mycrop.noScanDesc': 'स्वास्थ्य ट्रैकिंग शुरू करने के लिए अपनी पहली फसल स्कैन करें।',
    'mycrop.scanFirst': 'पहली फसल स्कैन करें',
    'mycrop.history': 'स्कैन इतिहास',

    'landing.getStarted': 'शुरू करें',
    'landing.createProfile': 'शुरू करने के लिए किसान प्रोफाइल बनाएं',
    'landing.welcomeBack': 'वापसी पर स्वागत',
    'landing.enterName': 'जारी रखने के लिए नाम दर्ज करें',
    'landing.fullName': 'पूरा नाम *',
    'landing.phone': 'फोन नंबर',
    'landing.village': 'गांव / शहर',
    'landing.create': 'प्रोफाइल बनाएं',
    'landing.continue': 'जारी रखें',
    'landing.hasProfile': 'पहले से प्रोफ़ाइल है? त्वरित लॉगिन',
    'landing.newHere': 'नए हैं? प्रोफ़ाइल बनाएं',
    'landing.heroTitle1': 'स्मार्ट खेती',
    'landing.heroTitle2': 'यहां शुरू होती है।',
    'landing.heroDesc': 'अपनी फसलों को स्कैन करें, तुरंत रोगों का पता लगाएं, सटीक उपचार योजनाएं प्राप्त करें।',
    'landing.tag': 'AI-संचालित फसल बुद्धिमत्ता',

    'agent.title': 'AgriLens AI',
    'agent.subtitle': 'आपका कृषि सहायक',
    'agent.placeholder': 'फसल, मौसम, रोग के बारे में पूछें...',
    'agent.greeting': 'नमस्ते! मैं आपका AgriLens कृषि सहायक हूं। फसलों, रोगों, उर्वरकों, मौसम के बारे में कुछ भी पूछें।',

    'eshop.title': 'अनुशंसित उत्पाद',
    'eshop.subtitle': 'आपके फसल विश्लेषण पर आधारित',
    'eshop.fertilizers': 'सुझाए गए उर्वरक',
    'eshop.pesticides': 'अनुशंसित कीटनाशक',
    'eshop.organic': 'जैविक विकल्प',
    'eshop.comingSoon': 'जल्द आ रहा है',
    'eshop.addToCart': 'कार्ट में डालें',
    'eshop.close': 'बंद करें',

    'common.healthy': 'स्वस्थ',
    'common.loading': 'लोड हो रहा...',

    'comm.title': 'कृषि समुदाय',
    'comm.subtitle': 'जुड़ें, नवाचार साझा करें, और एक साथ बढ़ें',
    'comm.placeholder': 'एक अपडेट साझा करें, सवाल पूछें, या नया नवाचार पोस्ट करें...',
    'comm.addImage': 'फोटो जोड़ें',
    'comm.addLink': 'नवाचार लिंक जोड़ें',
    'comm.post': 'पोस्ट करें',
    'comm.you': 'आप',
    'comm.justNow': 'अभी-अभी',
    'comm.verified': 'सत्यापित अन्वेषक',
    'comm.purchase': 'खरीदें / उपकरण विवरण देखें',
    'comm.trending': 'कृषि में ट्रेंडिंग',
    'comm.topInnovators': 'शीर्ष अन्वेषक',
    'comm.follow': 'फॉलो करें',
    'comm.tech': 'तकनीक',
    'comm.cropsCat': 'फसलें',
    'comm.market': 'बाज़ार',
    'comm.innovationCat': 'नवाचार',
    'comm.posts': 'पोस्ट',

    'landing.featDetect': 'तुरुंत रोग का पता लगाना',
    'landing.featDetectDesc': 'एक तस्वीर अपलोड करें और सेकंडों में AI विश्लेषण प्राप्त करें',
    'landing.featPlan': 'व्यक्तिगत फसल योजनाएं',
    'landing.featPlanDesc': 'आपकी फसल के लिए सिंचाई, कीटनाशक और देखभाल के कार्यक्रम',
    'landing.featWeather': 'मौसम की बुद्धिमत्ता',
    'landing.featWeatherDesc': 'स्मार्ट खेती की सिफारिशों के साथ 7 दिनों का पूर्वानुमान',
    'landing.loginPhonePass': 'जारी रखने के लिए अपना फोन और पासवर्ड दर्ज करें',
    'landing.namePlaceholder': 'अपना नाम दर्ज करें',
    'landing.phoneReq': 'फ़ोन नंबर *',
    'landing.password': 'पासवर्ड *',
    'landing.locPlaceholder': 'वैकल्पिक',
    'landing.errNameRequired': 'पंजीकरण के लिए नाम आवश्यक है।',
    'landing.errPhoneRequired': 'फ़ोन नंबर आवश्यक है।',
    'landing.errPassLengths': 'पासवर्ड कम से कम 4 अक्षरों का होना चाहिए।',
    'landing.stat1': 'समर्थित फसल किस्में',
    'landing.stat2': 'रोग का पता लगाने की सटीकता',
    'landing.stat3': 'मौसम और सिंचाई डेटा',
    'landing.stat3val': 'मुफ़्त',
    'landing.stat4': 'AI-जनित रिपोर्ट',
    'landing.stat4val': 'तुरंत',

    'report.type': 'प्रकार',
    'report.dosage': 'खुराक',
    'report.apply': 'प्रयोग',
    'report.frequency': 'आवृत्ति',
    'report.warning': 'चेतावनी',
    'report.close': 'बंद करें',
    'report.saveAsImage': 'तस्वीर के रूप में सहेजें',
    'report.downloadPdf': 'PDF डाउनलोड करें',
    'report.share': 'शेयर करें',
    'report.diseaseDetected': 'रोग का पता चला',
    'report.treatmentPlan': 'उपचार योजना',
    'report.recommendedPesticides': 'अनुशंसित कीटनाशक',
    'report.organicAlternatives': 'जैविक विकल्प',
    'report.fertilizerSuggestions': 'उर्वरक सुझाव',
    'report.cropCareTips': 'फसल देखभाल के सुझाव',
    'report.analyzedBy': 'AgriLens AI द्वारा विश्लेषित',
    'report.scanAnother': 'एक और पत्ता स्कैन करें',
  },

  kn: {
    'nav.home': 'ಮುಖಪುಟ',
    'nav.myCrop': 'ನನ್ನ ಬೆಳೆ',
    'nav.scanner': 'ಸ್ಕ್ಯಾನರ್',
    'nav.weather': 'ಹವಾಮಾನ',
    'nav.encyclopedia': 'ವಿಶ್ವಕೋಶ',
    'nav.community': 'ಸಮುದಾಯ',
    'nav.logout': 'ಲಾಗ್ ಔಟ್',

    'home.welcome': 'ಮರಳಿ ಸ್ವಾಗತ,',
    'home.overview': 'ಇಂದಿನ ನಿಮ್ಮ ಕೃಷಿ ಅವಲೋಕನ',
    'home.currentCrop': 'ಪ್ರಸ್ತುತ ಬೆಳೆ',
    'home.weather': 'ಇಂದಿನ ಹವಾಮಾನ',
    'home.season': 'ಪ್ರಸ್ತುತ ಋತು',
    'home.tipOfDay': 'ಇಂದಿನ ಸಲಹೆ',
    'home.quickAccess': 'ತ್ವರಿತ ಪ್ರವೇಶ',
    'home.latestNews': 'ಇತ್ತೀಚಿನ ಕೃಷಿ ಸುದ್ದಿ',
    'home.enableLocation': 'ಸ್ಥಳ ಸಕ್ರಿಯಗೊಳಿಸಿ',
    'home.detecting': 'ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'home.cropScanner': 'ಬೆಳೆ ಸ್ಕ್ಯಾನರ್',
    'home.cropScannerDesc': 'AI ಚಾಲಿತ ರೋಗ ಪತ್ತೆ ಮತ್ತು ಚಿಕಿತ್ಸೆ',
    'home.weatherPlanner': 'ಹವಾಮಾನ ಯೋಜಕ',
    'home.weatherPlannerDesc': '7 ದಿನ ಮುನ್ಸೂಚನೆ ಮತ್ತು ನೀರಾವರಿ',
    'home.encyclopedia': 'ವಿಶ್ವಕೋಶ',
    'home.encyclopediaDesc': 'ಬೆಳೆ ಪ್ರೊಫೈಲ್ ಮತ್ತು ಬೆಳೆಯುವ ಮಾರ್ಗದರ್ಶಿ',
    'home.myCrop': 'ನನ್ನ ಬೆಳೆ',
    'home.myCropDesc': 'ವೈಯಕ್ತಿಕ ಬೆಳೆ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',

    'scanner.title': 'ಬೆಳೆ ಸ್ಕ್ಯಾನರ್',
    'scanner.subtitle': 'AI ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಬೆಳೆಯ ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    'scanner.dropPhoto': 'ಬೆಳೆಯ ಫೋಟೋ ಇಲ್ಲಿ ಹಾಕಿ',
    'scanner.browse': 'ಅಥವಾ ಬ್ರೌಸ್ ಮಾಡಿ — JPEG, PNG, WebP',
    'scanner.upload': 'ಫೋಟೋ ಅಪ್ಲೋಡ್',
    'scanner.takePhoto': 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    'scanner.analyzing': 'ಬೆಳೆ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    'scanner.wait': 'ಕೆಲವು ಸೆಕೆಂಡ್ ತಗಲಬಹುದು',
    'scanner.failed': 'ವಿಶ್ಲೇಷಣೆ ವಿಫಲ',
    'scanner.tryAgain': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    'scanner.scanAnother': 'ಮತ್ತೊಂದು ಬೆಳೆ ಸ್ಕ್ಯಾನ್',
    'scanner.tips': 'ಉತ್ತಮ ಫಲಿತಾಂಶಕ್ಕಾಗಿ ಸಲಹೆಗಳು',
    'scanner.shopBtn': 'ಉತ್ಪನ್ನ ಶಿಫಾರಸುಗಳು',

    'weather.title': 'ಹವಾಮಾನ ಮತ್ತು ನೀರಾವರಿ ಯೋಜಕ',
    'weather.subtitle': '7 ದಿನ ಮುನ್ಸೂಚನೆ ಮತ್ತು AI ನೀರಾವರಿ',
    'weather.locationRequired': 'ಸ್ಥಳ ಅಗತ್ಯ',
    'weather.retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    'weather.forecast': '7 ದಿನ ಮುನ್ಸೂಚನೆ',
    'weather.generatePlan': 'ನೀರಾವರಿ ಯೋಜನೆ ರಚಿಸಿ',
    'weather.cropName': 'ಬೆಳೆ ಹೆಸರು',
    'weather.generating': 'ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    'weather.genPlan': 'ಯೋಜನೆ ರಚಿಸಿ',
    'weather.weeklySummary': 'ವಾರದ ಸಾರಾಂಶ',
    'weather.dailySchedule': 'ದೈನಂದಿನ ನೀರಾವರಿ',
    'weather.pesticides': 'ಶಿಫಾರಸು ಕೀಟನಾಶಕಗಳು',
    'weather.irrigationTips': 'ನೀರಾವರಿ ಸಲಹೆಗಳು',
    'weather.agriIndex': 'ಕೃಷಿ ಹವಾಮಾನ ಸೂಚ್ಯಂಕ',
    'weather.soilMoisture': 'ಮಣ್ಣಿನ ತೇವಾಂಶ',
    'weather.soilTemp': 'ಮಣ್ಣಿನ ಉಷ್ಣತೆ',
    'weather.evapotranspiration': 'ಆವಿಯಾಗುವಿಕೆ (ET₀)',
    'weather.sunshine': 'ಸೂರ್ಯ ಪ್ರಕಾಶ',
    'weather.alerts': 'ಹವಾಮಾನ ಅಪಾಯ ಎಚ್ಚರಿಕೆ',
    'weather.humidity': 'ತೇವಾಂಶ',

    'encyclopedia.title': 'ಬೆಳೆ ವಿಶ್ವಕೋಶ',
    'encyclopedia.subtitle': 'AI ಬೆಳೆ ಮಾರ್ಗದರ್ಶಿ ಹುಡುಕಿ',
    'encyclopedia.search': 'ಬೆಳೆ ಹೆಸರು ಅಥವಾ ವರ್ಗ ಹುಡುಕಿ...',
    'encyclopedia.backToCrops': 'ಬೆಳೆಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
    'encyclopedia.generating': 'ಪ್ರೊಫೈಲ್ ರಚಿಸಲಾಗುತ್ತಿದೆ',

    'mycrop.title': 'ನನ್ನ ಬೆಳೆ',
    'mycrop.subtitle': 'ಪ್ರಸ್ತುತ ಬೆಳೆ ಸ್ಥಿತಿ ಮತ್ತು ಸ್ಕ್ಯಾನ್ ಇತಿಹಾಸ',
    'mycrop.rescan': 'ಮತ್ತೆ ಸ್ಕ್ಯಾನ್',
    'mycrop.viewIrrigation': 'ನೀರಾವರಿ ಯೋಜನೆ',
    'mycrop.noScan': 'ಇನ್ನೂ ಬೆಳೆ ಸ್ಕ್ಯಾನ್ ಆಗಿಲ್ಲ',
    'mycrop.noScanDesc': 'ಆರೋಗ್ಯ ಟ್ರ್ಯಾಕಿಂಗ್ ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮೊದಲ ಬೆಳೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ।',
    'mycrop.scanFirst': 'ಮೊದಲ ಬೆಳೆ ಸ್ಕ್ಯಾನ್',
    'mycrop.history': 'ಸ್ಕ್ಯಾನ್ ಇತಿಹಾಸ',

    'landing.getStarted': 'ಪ್ರಾರಂಭಿಸಿ',
    'landing.createProfile': 'ಪ್ರಾರಂಭಿಸಲು ರೈತ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ',
    'landing.welcomeBack': 'ಮರಳಿ ಸ್ವಾಗತ',
    'landing.enterName': 'ಮುಂದುವರಿಸಲು ಹೆಸರು ನಮೂದಿಸಿ',
    'landing.fullName': 'ಪೂರ್ಣ ಹೆಸರು *',
    'landing.phone': 'ಫೋನ್ ಸಂಖ್ಯೆ',
    'landing.village': 'ಹಳ್ಳಿ / ಪಟ್ಟಣ',
    'landing.create': 'ಪ್ರೊಫೈಲ್ ರಚಿಸಿ',
    'landing.continue': 'ಮುಂದುವರಿಸಿ',
    'landing.hasProfile': 'ಈಗಾಗಲೇ ಪ್ರೊಫೈಲ್ ಇದೆಯೇ? ತ್ವರಿತ ಲಾಗಿನ್',
    'landing.newHere': 'ಹೊಸಬರೇ? ಪ್ರೊಫೈಲ್ ರಚಿಸಿ',
    'landing.heroTitle1': 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿ',
    'landing.heroTitle2': 'ಇಲ್ಲಿ ಪ್ರಾರಂಭ.',
    'landing.heroDesc': 'ಬೆಳೆಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ, ರೋಗಗಳನ್ನು ತಕ್ಷಣ ಪತ್ತೆ ಮಾಡಿ, ನಿಖರ ಚಿಕಿತ್ಸೆ ಯೋಜನೆಗಳನ್ನು ಪಡೆಯಿರಿ.',
    'landing.tag': 'AI ಚಾಲಿತ ಬೆಳೆ ಬುದ್ಧಿಮತ್ತೆ',

    'agent.title': 'AgriLens AI',
    'agent.subtitle': 'ನಿಮ್ಮ ಕೃಷಿ ಸಹಾಯಕ',
    'agent.placeholder': 'ಬೆಳೆ, ಹವಾಮಾನ, ರೋಗಗಳ ಬಗ್ಗೆ ಕೇಳಿ...',
    'agent.greeting': 'ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ AgriLens ಕೃಷಿ ಸಹಾಯಕ. ಬೆಳೆ, ರೋಗ, ಗೊಬ್ಬರ, ಹವಾಮಾನ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ.',

    'eshop.title': 'ಶಿಫಾರಸು ಉತ್ಪನ್ನಗಳು',
    'eshop.subtitle': 'ನಿಮ್ಮ ಬೆಳೆ ವಿಶ್ಲೇಷಣೆ ಆಧಾರಿತ',
    'eshop.fertilizers': 'ಸೂಚಿತ ರಸಗೊಬ್ಬರಗಳು',
    'eshop.pesticides': 'ಶಿಫಾರಸು ಕೀಟನಾಶಕಗಳು',
    'eshop.organic': 'ಸಾವಯವ ಪರ್ಯಾಯಗಳು',
    'eshop.comingSoon': 'ಶೀಘ್ರದಲ್ಲಿ',
    'eshop.addToCart': 'ಕಾರ್ಟ್ ಗೆ ಸೇರಿಸಿ',
    'eshop.close': 'ಮುಚ್ಚಿ',

    'common.healthy': 'ಆರೋಗ್ಯಕರ',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',

    'comm.title': 'ಕೃಷಿ ಸಮುದಾಯ',
    'comm.subtitle': 'ಸಂಪರ್ಕಿಸಿ, ಆವಿಷ್ಕಾರಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ ಮತ್ತು ಒಟ್ಟಿಗೆ ಬೆಳೆಯಿರಿ',
    'comm.placeholder': 'ಅಪ್ಡೇಟ್ ಹಂಚಿಕೊಳ್ಳಿ, ಪ್ರಶ್ನೆ ಕೇಳಿ, ಅಥವಾ ಹೊಸ ಆವಿಷ್ಕಾರವನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ...',
    'comm.addImage': 'ಚಿತ್ರ ಸೇರಿಸಿ',
    'comm.addLink': 'ಆವಿಷ್ಕಾರ ಲಿಂಕ್ ಸೇರಿಸಿ',
    'comm.post': 'ಪೋಸ್ಟ್',
    'comm.you': 'ನೀವು',
    'comm.justNow': 'ಈಗಷ್ಟೇ',
    'comm.verified': 'ಪರಿಶೀಲಿಸಿದ ಆವಿಷ್ಕಾರಕ',
    'comm.purchase': 'ಖರೀದಿಸಿ / ಉಪಕರಣದ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'comm.trending': 'ಕೃಷಿಯಲ್ಲಿ ಒಲವು',
    'comm.topInnovators': 'ಉನ್ನತ ಆವಿಷ್ಕಾರಕರು',
    'comm.follow': 'ಅನುಸರಿಸಿ',
    'comm.tech': 'ತಂತ್ರಜ್ಞಾನ',
    'comm.cropsCat': 'ಬೆಳೆಗಳು',
    'comm.market': 'ಮಾರುಕಟ್ಟೆ',
    'comm.innovationCat': 'ಆವಿಷ್ಕಾರ',
    'comm.posts': 'ಪೋಸ್ಟ್‌ಗಳು',

    'landing.featDetect': 'ಕ್ಷಿಪ್ರ ರೋಗ ಪತ್ತೆ',
    'landing.featDetectDesc': 'ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ಸೆಕೆಂಡುಗಳಲ್ಲಿ AI ವಿಶ್ಲೇಷಣೆ ಪಡೆಯಿರಿ',
    'landing.featPlan': 'ವೈಯಕ್ತೀಕರಿಸಿದ ಬೆಳೆ ಯೋಜನೆಗಳು',
    'landing.featPlanDesc': 'ನಿಮ್ಮ ಬೆಳೆಗಾಗಿ ನೀರಾವರಿ, ಕೀಟನಾಶಕ ಮತ್ತು ಆರೈಕೆ ವೇಳಾಪಟ್ಟಿಗಳು',
    'landing.featWeather': 'ಹವಾಮಾನ ಬುದ್ಧಿವಂತಿಕೆ',
    'landing.featWeatherDesc': 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಶಿಫಾರಸುಗಳೊಂದಿಗೆ 7-ದಿನದ ಮುನ್ಸೂಚನೆ',
    'landing.loginPhonePass': 'ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ಫೋನ್ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    'landing.namePlaceholder': 'ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    'landing.phoneReq': 'ದೂರವಾಣಿ ಸಂಖ್ಯೆ *',
    'landing.password': 'ಪಾಸ್ವರ್ಡ್ *',
    'landing.locPlaceholder': 'ಐಚ್ಛಿಕ',
    'landing.errNameRequired': 'ನೋಂದಾಯಿಸಲು ಹೆಸರು ಅಗತ್ಯವಿದೆ.',
    'landing.errPhoneRequired': 'ಫೋನ್ ಸಂಖ್ಯೆ ಅಗತ್ಯವಿದೆ.',
    'landing.errPassLengths': 'ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 4 ಅಕ್ಷರಗಳಾಗಿರಬೇಕು.',
    'landing.stat1': 'ಬೆಂಬಲಿತ ಬೆಳೆ ಪ್ರಭೇದಗಳು',
    'landing.stat2': 'ರೋಗ ಪತ್ತೆ ನಿಖರತೆ',
    'landing.stat3': 'ಹವಾಮಾನ ಮತ್ತು ನೀರಾವರಿ ಡೇಟಾ',
    'landing.stat3val': 'ಉಚಿತ',
    'landing.stat4': 'AI-ರಚಿಸಿದ ವರದಿಗಳು',
    'landing.stat4val': 'ತತ್ಕ್ಷಣ',

    'report.type': 'ಪ್ರಕಾರ',
    'report.dosage': 'ಡೋಸೇಜ್',
    'report.apply': 'ಅನ್ವಯಿಸಿ',
    'report.frequency': 'ಆವರ್ತನ',
    'report.warning': 'ಎಚ್ಚರಿಕೆ',
    'report.close': 'ಮುಚ್ಚಿ',
    'report.saveAsImage': 'ಚಿತ್ರವಾಗಿ ಉಳಿಸಿ',
    'report.downloadPdf': 'PDF ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    'report.share': 'ಹಂಚಿಕೊಳ್ಳಿ',
    'report.diseaseDetected': 'ರೋಗ ಪತ್ತೆಯಾಗಿದೆ',
    'report.treatmentPlan': 'ಚಿಕಿತ್ಸಾ ಯೋಜನೆ',
    'report.recommendedPesticides': 'ಶಿಫಾರಸು ಕೀಟನಾಶಕಗಳು',
    'report.organicAlternatives': 'ಸಾವಯವ ಪರ್ಯಾಯಗಳು',
    'report.fertilizerSuggestions': 'ರಸಗೊಬ್ಬರ ಸಲಹೆಗಳು',
    'report.cropCareTips': 'ಬೆಳೆ ಆರೈಕೆ ಸಲಹೆಗಳು',
    'report.analyzedBy': 'AgriLens AI ನಿಂದ ವಿಶ್ಲೇಷಿಸಲಾಗಿದೆ',
    'report.scanAnother': 'ಮತ್ತೊಂದು ಎಲೆಯನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try {
      return localStorage.getItem(STORAGE_KEY) || 'en';
    } catch {
      return 'en';
    }
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.setAttribute('lang', lang);
  }, [lang]);

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations.en?.[key] || key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
